name: Unit Tests

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
  release:
    branches:
      - master
      
env:
  PROJECT: ${{ github.event.repository.name }}.xcodeproj
  SCHEME: ${{ github.event.repository.name }}


jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check environment variables
        run: |
         echo PROJECT: $PROJECT
         echo SCHEME: $SCHEME
      - name: Check xcodebuild version
        run: |
          xcodebuild -version
          type -a xcodebuild
      - name: Check xcode-select version
        run: |
          xcode-select -version
          type -a xcode-select
      - name: Clean xcodeproject
        run: |
          xcodebuild clean
      - name: Build xcodeproject
        run: |
          xcodebuild build -project $PROJECT -scheme $SCHEME CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

